### ISSUE TITLE
Oracle Cloud Infrastructure CLI

### ISSUE THREAD

**Issue by satokaz** [satokaz/hitorigoto#21]
Apple M1 機 で、arm64 build できないので、`arch -arch x86_64 /bin/zsh -l` とかして、x86_64 でインストールを実行すること。

* https://github.com/oracle/oci-cli

**Comment by satokaz** [comment]
Solaris 11.4 への install。
error になっている。後でチェック

```
12:28:15-kazus@solaris~$ bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16053  100 16053    0     0  44101      0 --:--:-- --:--:-- --:--:-- 44101

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.14.4/scripts/install/install.py to /tmp/oci_cli_install_tmp_OVbQ.
######################################################################### 100.0%
Running install script.
python3 /tmp/oci_cli_install_tmp_OVbQ 
-- Verifying Python version.
-- Python version 3.7.9 okay.

===> In what directory would you like to place the install? (leave blank to use '/export/home/kazus/lib/oracle-cli'): 
-- Creating directory '/export/home/kazus/lib/oracle-cli'.
-- We will install at '/export/home/kazus/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/export/home/kazus/bin'): 
-- The executable will be in '/export/home/kazus/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/export/home/kazus/bin/oci-cli-scripts'): 
-- Creating directory '/export/home/kazus/bin/oci-cli-scripts'.
-- The scripts will be in '/export/home/kazus/bin/oci-cli-scripts'.

===> Currently supported optional packages are: ['db (will install cx_Oracle)']
What optional CLI packages would you like to be installed (comma separated names; press enter if you don't need any optional packages)?: 
-- The optional packages installed will be ''.
-- Trying to use python3 venv.
-- Executing: ['/usr/bin/python3', '-m', 'venv', '/export/home/kazus/lib/oracle-cli']
-- Executing: ['/export/home/kazus/lib/oracle-cli/bin/pip', 'install', '--upgrade', 'pip']
Collecting pip
  Downloading pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 4.1 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-20.3.3
-- Executing: ['/export/home/kazus/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmpyrmpuabv', 'wheel', '--upgrade']
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
-- Executing: ['/export/home/kazus/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmpyrmpuabv', 'oci_cli', '--upgrade']
Collecting oci_cli
  Downloading oci_cli-2.18.0-py2.py3-none-any.whl (12.5 MB)
     |████████████████████████████████| 12.5 MB 10.3 MB/s 
Collecting arrow==0.14.7
  Downloading arrow-0.14.7-py2.py3-none-any.whl (39 kB)
Collecting click==6.7
  Downloading click-6.7-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 15.3 MB/s 
Collecting configparser==4.0.2
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting cryptography==3.2.1
  Downloading cryptography-3.2.1.tar.gz (540 kB)
     |████████████████████████████████| 540 kB 15.5 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /export/home/kazus/lib/oracle-cli/bin/python3 /export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hh2orif1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (128 lines):
  Collecting cffi!=1.11.3,>=1.8
    Downloading cffi-1.14.4.tar.gz (471 kB)
  Collecting wheel
    Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting pycparser
    Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Collecting setuptools>=40.6.0
    Downloading setuptools-51.3.3-py3-none-any.whl (786 kB)
  Building wheels for collected packages: cffi
    Building wheel for cffi (setup.py): started
    Building wheel for cffi (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /export/home/kazus/lib/oracle-cli/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b4itjadj
         cwd: /tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/
    Complete output (50 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.solaris-2.11-i86pc.64bit-3.7
    creating build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/model.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/commontypes.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/error.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/cparser.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/ffiplatform.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/pkgconfig.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/vengine_gen.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/api.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/lock.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/__init__.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/verifier.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/recompiler.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/_cffi_include.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/parse_c_type.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/_embedding.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.solaris-2.11-i86pc.64bit-3.7
    creating build/temp.solaris-2.11-i86pc.64bit-3.7/c
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -D_REENTRANT -m64 -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/lib/libffi-3.2.1/include -I/export/home/kazus/lib/oracle-cli/include -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.solaris-2.11-i86pc.64bit-3.7/c/_cffi_backend.o -DFFI_NO_RAW_API
    In file included from /usr/lib/libffi-3.2.1/include/ffi.h:67,
                     from c/_cffi_backend.c:15:
    /usr/lib/libffi-3.2.1/include/ffitarget.h:154:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
      154 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
          |  ^~~~~
    In file included from c/_cffi_backend.c:15:
    /usr/lib/libffi-3.2.1/include/ffi.h:493:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
      493 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
          |  ^~~~~
    In file included from c/malloc_closure.h:6,
                     from c/_cffi_backend.c:121:
    /usr/lib/libffi-3.2.1/include/ffi.h:493:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
      493 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
          |  ^~~~~
    c/_cffi_backend.c: In function 'fb_prepare_cif':
    c/_cffi_backend.c:5887:16: warning: comparison of integer expressions of different signedness: 'ffi_status' and 'int' [-Wsign-compare]
     5887 |     if (status == -1) {
          |                ^~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for cffi
    Running setup.py clean for cffi
  Failed to build cffi
  Installing collected packages: pycparser, wheel, setuptools, cffi
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /export/home/kazus/lib/oracle-cli/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-99gbr795/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-hh2orif1/overlay --compile --install-headers /tmp/pip-build-env-hh2orif1/overlay/include/site/python3.7/cffi
           cwd: /tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/
      Complete output (50 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.solaris-2.11-i86pc.64bit-3.7
      creating build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/model.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/commontypes.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/error.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/cparser.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/api.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/lock.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/__init__.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/verifier.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/recompiler.py -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/_embedding.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.solaris-2.11-i86pc.64bit-3.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.solaris-2.11-i86pc.64bit-3.7
      creating build/temp.solaris-2.11-i86pc.64bit-3.7/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -D_REENTRANT -m64 -O3 -ffile-prefix-map=..=. -O2 -fPIC -DPIC -march=opteron -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/lib/libffi-3.2.1/include -I/export/home/kazus/lib/oracle-cli/include -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.solaris-2.11-i86pc.64bit-3.7/c/_cffi_backend.o -DFFI_NO_RAW_API
      In file included from /usr/lib/libffi-3.2.1/include/ffi.h:67,
                       from c/_cffi_backend.c:15:
      /usr/lib/libffi-3.2.1/include/ffitarget.h:154:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
        154 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
            |  ^~~~~
      In file included from c/_cffi_backend.c:15:
      /usr/lib/libffi-3.2.1/include/ffi.h:493:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
        493 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
            |  ^~~~~
      In file included from c/malloc_closure.h:6,
                       from c/_cffi_backend.c:121:
      /usr/lib/libffi-3.2.1/include/ffi.h:493:2: error: #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
        493 | #error "32-bits header file used for 64-bits build. You may need to set PKG_CONFIG_PATH=/usr/lib/64/pkgconfig."
            |  ^~~~~
      c/_cffi_backend.c: In function 'fb_prepare_cif':
      c/_cffi_backend.c:5887:16: warning: comparison of integer expressions of different signedness: 'ffi_status' and 'int' [-Wsign-compare]
       5887 |     if (status == -1) {
            |                ^~
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /export/home/kazus/lib/oracle-cli/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l8gaxw63/cffi_bdbc1ece07144ae488cfe8954ba35cf3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-99gbr795/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-hh2orif1/overlay --compile --install-headers /tmp/pip-build-env-hh2orif1/overlay/include/site/python3.7/cffi Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /export/home/kazus/lib/oracle-cli/bin/python3 /export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hh2orif1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_OVbQ", line 685, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_OVbQ", line 640, in main
    install_cli(install_dir, tmp_dir, args.oci_cli_version, OPTIONAL_FEATURES)
  File "/tmp/oci_cli_install_tmp_OVbQ", line 298, in install_cli
    exec_command(cmd, env=env)
  File "/tmp/oci_cli_install_tmp_OVbQ", line 141, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/export/home/kazus/lib/oracle-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmpyrmpuabv', 'oci_cli', '--upgrade']' returned non-zero exit status 1.

```

**Comment by satokaz** [comment]
` PKG_CONFIG_PATH=/usr/lib/64/pkgconfig` をセットしてやり直したら installできた。
しかし、link している openssl が古くって実行できない。

```
kazus@solaris:~$ oci
Traceback (most recent call last):
  File "/export/home/kazus/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/__init__.py", line 59, in <module>
    __import__(ALL_SERVICES_DIR + '.' + modname1 + '.src.' + oci_cli_module_name + "." + extended_module)
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/services/dts/src/oci_cli_appliance_export_job/applianceexportjob_cli_extended.py", line 22, in <module>
    from services.dts.src.oci_cli_dts.physicalappliance_cli_extended import pa_init_auth_helper, pa_unlock_helper, \
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/services/dts/src/oci_cli_dts/physicalappliance_cli_extended.py", line 26, in <module>
    from services.dts.src.oci_cli_dts.appliance_init_auth import InitAuth
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/services/dts/src/oci_cli_dts/appliance_init_auth.py", line 10, in <module>
    from services.dts.src.oci_cli_dts.appliance_cert_manager import ApplianceCertManager
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/services/dts/src/oci_cli_dts/appliance_cert_manager.py", line 6, in <module>
    import OpenSSL
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 222, in <module>
    _verify_openssl_version(Binding.lib)
  File "/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 183, in _verify_openssl_version
    "You are linking against OpenSSL 1.0.2, which is no longer "
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
```

**Comment by satokaz** [comment]
`export CRYPTOGRAPHY_ALLOW_OPENSSL_102=1 ` をセットしてあげれば warning が出るが、実行はできる:


```
$ export CRYPTOGRAPHY_ALLOW_OPENSSL_102=1 
kazus@solaris:~$ oci
/export/home/kazus/lib/oracle-cli/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:179: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will completely remove support for it.
  utils.CryptographyDeprecationWarning,
Usage: oci [OPTIONS] COMMAND [ARGS]...
```

**Comment by satokaz** [comment]
oci-cli 内部で利用している pyca/cryptography (38.0.4)の build 、35.0.0 から Rust 必須(1.48.0 以降)になっている
この記事を書いた Solaris 11.4 SRU 28 の環境は、何かのタイミングで既に rustc と cargo パッケージがインストールされていたので大丈夫だった感じ

**Comment by satokaz** [comment]
Solaris 11.4 SRU 52
$ oci -version
3.22.0

```
# pkg install developer/rust/rustc
# pkg install developer/rust/cargo
```

**Comment by satokaz** [comment]
SPARC な Solaris 11.4 SRU 54 環境でも oci-cli が欲しかったので。
```sh
$ uname -a
SunOS solaris-t4-4 5.11 11.4.54.138.1 sun4v sparc sun4v non-virtualized
```

mediator に `default@1.1 ` がない。。。
```sh
$ pkg mediator -a openssl
MEDIATOR  VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
openssl   vendor            vendor     default@1.0
openssl   vendor            vendor     default
openssl   system            system     fips-140@1.0
openssl   system            system     fips-140
```

rustc と cargo を追加して、
```sh
# pkg install developer/rust/rustc
# pkg install developer/rust/cargo
```

環境変数で OpenSSL 1.1 を見つけれるようにして、
```sh
$ export PKG_CONFIG_PATH=/usr/openssl/1.1/pkgconfig/64/:/usr/lib/64/pkgconfig
$ export CFLAGS="$(pkg-config --cflags libffi --libs libcrypto libssl)"
```

できた。

**Comment by satokaz** [comment]
Solaris 11.4 SRU 82

`export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1`

> cryptography ライブラリは OpenSSL の内部関数を使っていますが、OpenSSL 3.0 以降ではレガシーアルゴリズム（例：MD5、RC4など）を使うには「レガシープロバイダ」を明示的に有効にする必要があるので、それを回避するために上記の環境変数をセットする

```
# pkg install developer/rust/rustc
# pkg install developer/rust/cargo
```


```
$ oci -version
3.63.0
```
